### ISSUE TITLE
Docker volume --driver weird behaviour

### ISSUE THREAD

**Issue by Farfaday** [rexray/rexray#1032]
# Summary
My ceph cluster in running Luminous. I am using rexray from the docker plugin.

I get this weird behaviour:

```shell
  # docker volume ls
DRIVER              VOLUME NAME
rexray              percona1
  # docker volume create --driver rexray/rbd --opt=size=1000 --name percona2
Error response from daemon: create percona2: VolumeDriver.Create: {"Error":"unable to get rbd info"}
  # docker volume ls
DRIVER              VOLUME NAME
rexray              percona1
  # docker volume create --driver rexray --opt=size=1000 --name percona2
percona2
  # rbd ls
percona1
percona2
  # docker volume create --driver rexray/rbd --opt=size=1000 --name percona2
Error response from daemon: create percona2: driver 'rexray' already has volume 'percona2': volume name must be unique
  # docker volume create --driver rexray/rbd --opt=size=1000 --name percona3
Error response from daemon: create percona3: VolumeDriver.Create: {"Error":"unable to get rbd info"}
```

Doing upper querry gives me following errors in the output of **rexray restart** 
```shell
ERRO[1728] resource not found                            host=unix:///var/run/rexray/693997673.sock instanceID=rbd=10.112.51.12 resourceID=percona2 route=volumeInspect server=foul-gargoyle-ec service=rbd storageDriver=rbd task=0 time=1505411918873 tls=false txCR=1505411918 txID=d8a4972d-e597-4cd4-4c12-ce172223b2d2

ERRO[1728] error: api call failed                        error.resourceID=percona2 host=unix:///var/run/rexray/693997673.sock route=volumeInspect server=foul-gargoyle-ec time=1505411918874 tls=false txCR=1505411918 txID=d8a4972d-e597-4cd4-4c12-ce172223b2d2

ERRO[1728] /VolumeDriver.Get: error getting volume       error.status=404 error.inner.resourceID=percona2 host=unix:///var/run/rexray/693997673.sock integrationDriver=linux osDriver=linux service=rbd storageDriver=libstorage time=1505411918875

ERRO[1741] resource not found                            host=unix:///var/run/rexray/693997673.sock instanceID=rbd=10.112.51.12 resourceID=percona3 route=volumeInspect server=foul-gargoyle-ec service=rbd storageDriver=rbd task=0 time=1505411932192 tls=false txCR=1505411932 txID=7e1bd018-1080-41b0-6326-5a3f8e1d647f

ERRO[1741] error: api call failed                        error.resourceID=percona3 host=unix:///var/run/rexray/693997673.sock route=volumeInspect server=foul-gargoyle-ec time=1505411932192 tls=false txCR=1505411932 txID=7e1bd018-1080-41b0-6326-5a3f8e1d647f

ERRO[1741] /VolumeDriver.Get: error getting volume       error.inner.resourceID=percona3 error.status=404 host=unix:///var/run/rexray/693997673.sock integrationDriver=linux osDriver=linux service=rbd storageDriver=libstorage time=1505411932192

```

# Bug Reports
My ceph cluster is running Luminous, but the krbd kernel client should not have changed it's behaviour. Running kernel 4.4 from Ubuntu Xenial repo.

My question is in fact:
Why is the volume creation working with --driver rexray and not with --driver rexray/rbd ?

## Version
Please paste the output of `rexray version`. For example:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Tue, 12 Sep 2017 23:18:02 CEST
```

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```yaml
libstorage:
  service: rbd
  integration:     
    volume:
      operations:
        create:
          default:
            size: 100G
rbd:
  defaultPool: rbd
```

**Comment by nohtyp** [comment]
@Farfaday I am using giant (0.87) and was wondering if this command results in an error or retrieves the info about the volume:

rbd info --pool <pool name> percona1 --format json

I am just wondering if that's why the driver can't gather information on the volumes.  I am looking at your issue as a way to fix my issue (https://github.com/codedellemc/rexray/issues/1052) and maybe they are the same sorta issue.

**Comment by codenrhoden** [comment]
@Farfaday A few more bits of information you can provide to help me think about this...

Were you using both `rexray` and the `rexray/rbd` Docker managed plugin on the same machine? I'm hoping not, because if you are that would be especially odd that one works and one doesn't...

You provided the output from `rexray version`, but not the version of the docker plugin. What does `docker plugin ls` show?

If this is something that is still tripping you up, I can give you instructions on how to enable debug logging in the Docker plugin, and how to extract those logs (it's not super straightforward to get access to them).

**Comment by Farfaday** [comment]
@nohtyp   Sorry for the long answer time:

```
rbd info --pool rbd percona1 --format json
{"name":"percona1","size":107374182400,"objects":25600,"order":22,"object_size":4194304,"block_name_prefix":"rbd_data.b158d6b8b4567","format":2,"features":["layering"],"flags":[],"create_timestamp":"Fri Sep 15 13:08:47 2017"}
```
Seems to work on 12.2.1 luminous

**Comment by Farfaday** [comment]
@codenrhoden Sorry for the long answer delay.
I'll first try to reproduce the issue against the latest version of rexray.

**Comment by mongrelion** [comment]
Has this issue been solved? Can we close this?
