### ISSUE TITLE
EFS Docker Volume Plug-in: require "nfs utilities" is conflicting for certain AWS AMIs

### ISSUE THREAD

**Issue by carl-utter** [rexray/rexray#1099]
### Scenario
We use Packer to build custom AMIs for our Docker Swarm running on AWS EC2. Our custom image leverages `ubuntu-xenial-16.04-amd64-server` and also includes both `Docker 17.03.0-ce` and `RexRay 0.9.1` for EFS Volumes. We have been installing `nfs-common` per the [AWS EC2 Ubuntu AMI](http://docs.aws.amazon.com/efs/latest/ug/mounting-fs.html) Instruction, and they seem to be working just fine.

However,  we wish to upgrade our custom AMIs to `Docker 17.09.0-ce` and `RexRay 0.11.0`, so I've been reading up on RexRay for that purpose.

### Issue
It seems that the [EFS Docker Volume Plug-in](https://hub.docker.com/r/rexray/efs/) requirement of `nfs utilities` _(I'm assuming you are meaning `nfs-utils`)_ is in conflict with the instructions at [AWS EC2 Ubuntu AMI](http://docs.aws.amazon.com/efs/latest/ug/mounting-fs.html) requirement of `nfs-common`

### Instruction Summary
> 4. Install the NFS client:
> For **Amazon Linux AMI** or **Red Hat Linux AMI** you should install `nfs-utils`
> For **Ubuntu Amazon EC2 AMI** you should install `nfs-common`
> 
> **Note:**
> If you choose the **Amazon Linux AMI 2016.03.0** or **Amazon Linux AMI 2016.09.0** Amazon Linux AMI when launching your Amazon EC2 instance, you won't need to install `nfs-utils` because it's already included in the AMI by default.

### Question
If I upgrade our custom AMIs to `RexRay 0.11.0`, while continuing to leverage `ubuntu-xenial-16.04-amd64-server`, then should I continue to install `nfs-common`, or should I install `nfs-utils` instead?

I cannot seem to find any distinction for this use-case other than AWS, so I wanted to double-check here.

_BTW- All of the the links on DockerHub to the ["Official Documentation"](http://rexray.readthedocs.io/en/stable/user-guide/docker-plugins/#elastic-file-system) are broken._

**Comment by clintkitson** [comment]
Hello @carl-utter,

Sorry for the delay. I don't see a problem with using that package instead, it is just expecting the nfs mount utility to be made available.
