### ISSUE TITLE
S3 doesn't work on Swarm bucket name containers invalid chars

### ISSUE THREAD

**Issue by bweston92** [rexray/rexray#1157]
# Summary

When using  Docker swarm and deploy a stack with the volumes defined like the following:

```
version: '3'
...
volumes:
	test:
		driver: rexray/s3fs
```

When deployed with have the prefix of the stack name for example `docker stack deploy -c ./deployment.yml web` will make the volume name `web_test` which then means the rexray/s3fs driver tries to make a bucket `web_test` which has invalid characters (the underscore). I have tried Setting `volumes.test.name` and `volumes.test.driver_opts.name` but neither overwrite the volume name.

## Version

`rexray/s3fs:latest`

## Expected Behavior

A) Either accept the name/bucket as a `driver_opts` so you can set `volumes.test.drivers_opts.bucket` .
B) Get word after the last underscore `web_test` => `test` and use as bucket name.

## Actual Behavior

Invalid bucket name from volume name in a Swarm stack deployment.

**Comment by akutz** [comment]
Hi @bweston92,

I'm inclined to say this is a Docker Swarm issue, but honestly we should be able to provide a simple fix for this. Could you please do me a favor and post a list of the invalid characters? Or rather, maybe it doesn't matter. How about this?

```yaml
rexray:
  invalidVolumeNameChars: "_|#$"
```

The above is just an example, but you get the idea. Basically we define a list of invalid characters for S3FS buckets and make sure the driver removes them from the name when performing operations on the volume?

**Comment by bweston92** [comment]
@akutz that would be a decent solution yes.
Would also be nice to specify the bucket name in the volume's `driver_opts`. Minio's minfs plugin had this as `bucket`.

**Comment by bweston92** [comment]
@akutz is this something that might come pretty soon?

**Comment by akutz** [comment]
Hi @bweston92,

We have a release schedule for February. @codenrhoden, can we please figure out how this issue fits with current priorities? Thanks!

**Comment by ptemmer** [comment]
Is this a problem that was introduced in the latest versions?
Reading a non related issue from 6 months ago, I got the feeling that rexray+s3+swarm used to work before:

https://github.com/thecodeteam/rexray/issues/908

**Comment by ptemmer** [comment]
I might as well misunderstood #908. Seems swarm is configured to use a previously created volume. Would that be a good alternative to circumvent the present issue?

**Comment by bweston92** [comment]
That Swarm as you say uses a volume already created, but for some reason when I did it that way it didn't find the volume, it was as if it wasn't accessible by Swarm because Swarm had not created it, I could be wrong.

**Comment by ptemmer** [comment]
@bweston92 I tried it earlier and didn't see any issue. Did you specify "external: true" in your volume specification in the compose file?

Nonetheless, I think the issue you reported is a basic feature that is required for rexray to work with Swarm.

**Comment by bweston92** [comment]
@ptemmer not to go off topic but yes, Rexray created the default volumes for buckets and I was unable to use them when targeting them with the following I just got Swarm waiting to schedule onto a node with the volume. (Docker 17.12)
```
volumes:
  myvolumename:
    external: true
```

**Comment by ptemmer** [comment]
Ah. I just did a quick test with with a single node swarm. So the volume was there anyway.

**Comment by ptemmer** [comment]
Any update on this?

**Comment by christiaangoossens** [comment]
I encountered this as well today, and found this workaround:

If you use compose file version 3.4, you can specify a `name` option for the volume like this:

```
volumes:
  myvolumename:
    name: myvolumename
    driver: rexray/s3fs
```

This will create a volume with the name `myvolumename`.

**Comment by christiaangoossens** [comment]
Related to #1120

**Comment by ptemmer** [comment]
Christiaan, works like a charm!!
Bedankt man

**Comment by bweston92** [comment]
@ptemmer it works with the `name` key?
I did try that, in my original message I put "I have tried Setting `volumes.test.name`  and `volumes.test.driver_opts.name` but neither overwrite the volume name."

Will try again later.

**Comment by christiaangoossens** [comment]
Could you check that you actually used compose version 3.4 or higher for the file? I've had it fail silently on 3.3

**Comment by bweston92** [comment]
@christiaangoossens that might be the case, will report back asap
