### ISSUE TITLE
[feature request] rados volume on multiple hosts

### ISSUE THREAD

**Issue by fentas** [rexray/rexray#1165]
I have a ceph cluster used by docker swarm via raxrey service.
Now I need to use a certain volume on multiple hosts but I am unable to do so.

Rexray seems to block this, setting the volume to "unavailable" if one or more rbd watcher exist.
The only thing I could find was in the docs:
> Until advisory locks are in place, it may be possible for a client to attach a volume that is already attached to another node.

Now my question: How?

Thanks a lot!

**Comment by fentas** [comment]
After looking at the code https://github.com/thecodeteam/rexray/blob/eaaa7b5cabcccae753ee2a71b279f648ace665e3/libstorage/drivers/storage/rbd/storage/rbd_storage.go

I could not find a straightforward or an intentional way to enable this.

A 'workaround' I could find, though, is to map rbd by myself. (exploding this https://github.com/thecodeteam/rexray/blob/eaaa7b5cabcccae753ee2a71b279f648ace665e3/libstorage/drivers/storage/rbd/storage/rbd_storage.go#L435)

```
rbd map <pool>/<image> --id <user> --keyring <secret>
```

After that `rexray volume mount` will work on all hosts. But then containers will not start.
> "VolumeDriver.Mount: ControllerPublishVolume failed: 0: ControllerPublishVolume failed: 0: rpc error: code = Unknown desc = volume in wrong state for attach"

Caused by this https://github.com/thecodeteam/rexray/blob/eaaa7b5cabcccae753ee2a71b279f648ace665e3/libstorage/drivers/storage/rbd/storage/rbd_storage.go#L308
Only the state "available" is accepted here hance beginning from the start.

Now I am at a dead end... Why do enforce this so much? 
Maybe adding a flag like `--I-agree-to-potential-damage` : )

**Comment by fentas** [comment]
@codenrhoden I would like to move this forward. 
I could try to make a pull request but I would like to figure out first what the best _solution/compromise_ is for RexRay? Or if you see any other obstacles?

**Comment by clintkitson** [comment]
@fentas The problem with this approach is that you would need a filesystem that is cluster-aware, ie. able to work properly when mounted to multiple hosts at the same time. Or the volume must not have a filesystem and the app itself is responsible for managing multiple writers. Doing EXT4/XFS on multiple hosts simultaneously just won't work.

**Comment by fentas** [comment]
The problem with ceph that I having here is that if one host mounts a ceph volume and it fails, it takes up to 3-10 minutes until this host disappears from the watchers lock. 

From the orchestration perspective, I know there is no instance running with this particular volume but it gets blocked because ceph watchers list is not up to date.

If this is solely a ceph problem, feel free to close this issue. 
Thanks a lot.

**Comment by clintkitson** [comment]
@fentas Yes I do believe this is a purely a ceph problem, @codenrhoden can you weigh in?

**Comment by fentas** [comment]
we switched to openebs. If someone else has this problem feel free to reopen.
