### ISSUE TITLE
Unable to disable/delete rexray/s3fs Docker plugin

### ISSUE THREAD

**Issue by ptemmer** [rexray/rexray#1176]
# Summary
After stopping and deleting all containers that were using rexray/s3fs as volume driver, I am unable to disable/uninstall the rexray/s3fs plugin. It says "in use".

```
docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

docker volume ls
DRIVER               VOLUME NAME
rexray/s3fs:latest   myprefix-vol

docker plugin disable rexray/s3fs
Error response from daemon: plugin rexray/s3fs:latest is in use
```

## Version
```
Rexray plugin rexray/s3fs:latest
"Description": "REX-Ray FUSE Driver for Amazon Simple Storage Service (S3FS)",
"DockerVersion": "17.11.0-ce",

docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
## Expected Behavior
Be able to delete the plugin

## Actual Behavior
It says the plugin is in use

## Steps To Reproduce
1. Install the rexray/s3fs plugin
2. Create a service that uses the plugin to create a volume
3. Stop and delete the service
4. Try to disable/uninstall the plugin

**Comment by christiaangoossens** [comment]
Simple fix, altough not the intended use, thus this stays a bug: restart the docker service and then remove the plugin. That worked for me multiple times.

**Comment by ptemmer** [comment]
@christiaangoossens Your trick worked on one node, unfortunately not on the other:

```
root@frontend1:/var/lib/docker# docker plugin disable rexray/s3fs
Error response from daemon: plugin rexray/s3fs:latest is in use
root@frontend1:/var/lib/docker# docker plugin disable rexray/s3fs
Error response from daemon: plugin rexray/s3fs:latest is in use
root@frontend1:/var/lib/docker# systemctl restart docker
root@frontend1:/var/lib/docker# docker plugin disable rexray/s3fs
Error response from daemon: plugin rexray/s3fs:latest is in use
root@frontend1:/var/lib/docker# systemctl restart docker
root@frontend1:/var/lib/docker# docker plugin disable rexray/s3fs
Error response from daemon: plugin rexray/s3fs:latest is in use
root@frontend1:/var/lib/docker# systemctl restart docker
root@frontend1:/var/lib/docker# docker plugin disable rexray/s3fs
Error response from daemon: plugin rexray/s3fs:latest is in use
```
I'm stuck with the current installed plugin. I just need to delete and reinstall with a S3FS option that I forgot. Quite disturbing...

**Comment by ptemmer** [comment]
Just noticed there is a --force option.
That worked.

**Comment by clintkitson** [comment]
Thanks @ptemmer, can you close this if you are good?

**Comment by ptemmer** [comment]
@clintkitson If you think this is not a bug, I'll close it.

**Comment by clintkitson** [comment]
@ptemmer I believe REX-Ray is functioning as it should here. It is the docker interface that is deciding how/when to close the managed plugin. Am I missing something?
