### ISSUE TITLE
Cinder driver relies on devices reported by Cinder

### ISSUE THREAD

**Issue by ederst** [rexray/rexray#1183]
# Summary
It seems that the REX-Ray Cinder driver relies on cinder to report the right device name, and also tries to force this by setting the device name by [basically passing](https://github.com/rexray/rexray/blob/v0.11.2/libstorage/drivers/storage/cinder/storage/cinder_storage.go#L623-L627) ```--device``` (if defined in ```opts```).

However, according to the [documentation](https://docs.openstack.org/nova/latest/user/block-device-mapping.html#intermezzo-problem-with-device-names):

> Using device names as the primary per-instance identifier, and exposing them in the API, is problematic for Nova mostly because several hypervisors Nova supports with its drivers can’t guarantee that the device names the guest OS assigns are the ones the user requested from Nova.

This seems especially true for users of libvirt (like we do), and there are some cases (we experienced them) where it is not possible for the REX-Ray cinder driver to correctly mount the volumes due to a mismatch between the device name reported by Cinder and the actual device name on the VM (= the OpenStack nova instance/server).

# Bug Reports

## Related reports/pull requests
* https://github.com/rexray/rexray/issues/346
* https://github.com/rexray/rexray/pull/357
Unfortunately, it does not seem that the code was merged.

## Version
We're using the rexray/cinder docker plugin:
```shell
"PluginReference": "docker.io/rexray/cinder:0.11.1"
```

## Expected Behavior
Cinder driver attaches volume to VM and mounts it.

## Actual Behavior
In certain cases, it seems that the udev magic of the VM or the order of attachments gets somehow in a state where Cinder reports a volume attached to /dev/vdX but the VM reports the device as /dev/vdY.

So the device gets actually attached (also visible via CLI and Horizon GUI), but the reported device there is simply wrong. For example: last time this happened Cinder reported /dev/vdf but on the VM the device was actually /dev/vdi.

## Steps To Reproduce
Unfortunately, I'm not sure how to reliably reproduce it, but it seems to happen regularly when attaching and detaching volumes multiple times without restarting the VMs running on OpenStack.
For example: I did this by running Jenkins builds starting Docker containers, attaching and detaching REX-ray Cinder volumes.

## Configuration Files
IMHO not relevant

### Docker plugin log
The log file contains actually the /dev/vdf vs /dev/vdi case described earlier:
```
Feb 26 04:39:20 somehost env[4998]: time="2018-02-26T04:39:20+01:00" level=info msg="time=\"2018-02-26T03:39:20Z\" level=debug msg=\"http header\" Libstorage-Localdevices=[cinder=/dev/dm-0::,/dev/vda::,/dev/vda1::,/dev/vda2::,/dev/vda3::,/dev/vda4::,/dev/vda6::,/dev/vda7::,/dev/vda9::,/dev/vdb::,/dev/vdc::,/dev/vdd::,/dev/vde::,/dev/vdh::,/dev/vdi::] host=\"unix:///var/run/rexray/055954627.sock\" route=volumeInspect server=cold-skinner-ki time=1519616360708 tls=false txCR=1519616360 txID=fd40cedf-936a-4f0b-78ce-a1952726fbfc " plugin=e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a
Feb 26 04:39:20 somehost env[4998]: time="2018-02-26T04:39:20+01:00" level=info msg="time=\"2018-02-26T03:39:20Z\" level=debug msg=\"getting storage service\" host=\"unix:///var/run/rexray/055954627.sock\" route=volumeInspect server=cold-skinner-ki service=cinder time=1519616360708 tls=false txCR=1519616360 txID=fd40cedf-936a-4f0b-78ce-a1952726fbfc " plugin=e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a
Feb 26 04:39:24 somehost env[4998]: time="2018-02-26T04:39:24+01:00" level=info msg="time=\"2018-02-26T03:39:24Z\" level=debug msg=\"manually calculating attachment state\" host=\"unix:///var/run/rexray/055954627.sock\" instanceID=\"cinder=bb137d5d-4e3b-4963-916a-cfc800147085\" route=volumeInspect server=cold-skinner-ki service=cinder storageDriver=cinder task=1 time=1519616364049 tls=false txCR=1519616354 txID=5c00b707-5c77-445c-4f37-67a575dc175f " plugin=e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a
Feb 26 04:39:24 somehost env[4998]: time="2018-02-26T04:39:24+01:00" level=info msg="time=\"2018-02-26T03:39:24Z\" level=debug msg=\"including volume\" attachmentState=attached host=\"unix:///var/run/rexray/055954627.sock\" instanceID=\"cinder=bb137d5d-4e3b-4963-916a-cfc800147085\" route=volumeInspect server=cold-skinner-ki service=cinder storageDriver=cinder task=1 time=1519616364049 tls=false txCR=1519616354 txID=5c00b707-5c77-445c-4f37-67a575dc175f " plugin=e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a
Feb 26 04:39:24 somehost env[4998]: time="2018-02-26T04:39:24+01:00" level=info msg="time=\"2018-02-26T03:39:24Z\" level=debug msg=\"driver is not StorageDriverVolInspectByName\" host=\"unix:///var/run/rexray/055954627.sock\" instanceID=\"cinder=bb137d5d-4e3b-4963-916a-cfc800147085\" route=volumeInspect server=cold-skinner-ki service=cinder storageDriver=cinder task=0 time=1519616364051 tls=false txCR=1519616360 txID=fd40cedf-936a-4f0b-78ce-a1952726fbfc " plugin=e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a
Feb 26 04:39:24 somehost env[4998]: time="2018-02-26T04:39:24+01:00" level=info msg="time=\"2018-02-26T03:39:24Z\" level=debug msg=\"getting storage service\" host=\"unix:///var/run/rexray/055954627.sock\" route=serviceInspect server=cold-skinner-ki service=cinder time=1519616364054 tls=false txCR=1519616364 txID=7220a732-0ae5-400d-6ac4-f784e0bf8f6f " plugin=e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a
Feb 26 04:39:24 somehost env[4998]: time="2018-02-26T04:39:24+01:00" level=info msg="time=\"2018-02-26T03:39:24Z\" level=error msg=\"docker-legacy: Mount: my-cinder-volume: failed: open /dev/vdf: no such file or directory\" host=\"unix:///var/run/rexray/055954627.sock\" integrationDriver=linux osDriver=linux service=cinder storageDriver=libstorage time=1519616364061 " plugin=e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a
Feb 26 04:39:24 somehost env[4998]: time="2018-02-26T04:39:24.190295727+01:00" level=error msg="Handler for POST /v1.32/containers/5aa953796a14a6852e7b064f154f9a56f72662db7a79e4daa577008f215b760f/start returned error: error while mounting volume '/var/lib/docker/plugins/e60c67bba2140d9df6092a9c2da33709b9c87cdfaffe899449523af47abbfc0a/rootfs': VolumeDriver.Mount: docker-legacy: Mount: my-cinder-volume: failed: open /dev/vdf: no such file or directory"
```

**Comment by ederst** [comment]
I tried to fix the issue, based on https://github.com/rexray/rexray/pull/357:
* https://github.com/ederst/rexray/tree/use-disk-by-id-for-cinder
* https://github.com/ederst/rexray/tree/use-disk-by-id-for-cinder_2

Also, I have built a docker plugin based on "use-disk-by-id-for-cinder_2" (obtainable from https://hub.docker.com/r/ederst/cinder/tags/), and I'm testing it.

If necessary I can create a pull request out of one of the solution, but I'm not a GO programmer, so I don't expect anything.

**Comment by ederst** [comment]
Since I've installed the Cinder driver Docker plugin with my code, no errors happened so far. FYI, if anyone is.

**Comment by kumy** [comment]
It seems the k8s had the same issue in the past https://github.com/kubernetes/kubernetes/issues/33128
