### ISSUE TITLE
Docs - invalid link

### ISSUE THREAD

**Issue by plainlystated** [rexray/rexray#1202]
Not sure if this is the right place to drop this issue, but I came across a dead link in the docs.

Page: https://rexray.readthedocs.io/en/stable/
Link text: Volume Driver Plugin
Link target: https://rexray.readthedocs.io/en/stable/user-guide/schedulers/dockermd (404)

Probably correct target(?): https://rexray.readthedocs.io/en/stable/user-guide/schedulers/docker

**Comment by clintkitson** [comment]
Yup, thanks for this we will get it corrected!

**Comment by Getty** [comment]
*bump* still wrong

**Comment by akutz** [comment]
The `stable` RTFD links will be wrong until we push a GA release. Check the  https://rexray.readthedocs.io/en/latest/ for the `HEAD` build of the docs.

**Comment by akutz** [comment]
I just checked, the link at  https://rexray.readthedocs.io/en/latest/` appears correctly.

**Comment by akutz** [comment]
Hi @Getty,

For now I've redirected https://rexray.rtfd.io to http://rexray.readthedocs.io/en/latest/ until we have a planned GA in sight.
