### ISSUE TITLE
"Resource not found" rexray/dobs

### ISSUE THREAD

**Issue by jaschaio** [rexray/rexray#1211]
I get the following error if I try to use a single rexray volume in several replicas across different nodes:

`VolumeDriver.Mount: docker-legacy: Mount: myvolume: failed: resource not found`

One replica works, the rest repeatedly fails because of the error.

The one that works is the one that has the volume actually attached.

This is probably due to DigitalOceans limitation that a single Block Storage Volume can only be attached to a single Droplet. But I wanted to make sure that this is indeed the case. Mabye somebody can point me into the right direction on how to share a volume between various replicas across several nodes on DigitalOcean.

**Comment by clintkitson** [comment]
That is correct. The `resource not found` error happens when a volume is mounted to a host. REX-Ray does not support mounting volumes to multiple hosts at this time.

**Comment by taraspos** [comment]
But why when I want each instance to create the volume for itself?
Instead of one working fine and rest goes into the crash loop. They should create volumes for itself with the same name.

I'm having this issue on the AWS.

Basically, I want two servers in the same AZ and RexRay should create volume for each of them. With the same name.

**Comment by cpxPratik** [comment]
@Trane9991, DO inherently does not support attaching volumes to more than one droplet. Refer https://www.digitalocean.com/docs/volumes/overview/#limits. May be you can use https://github.com/gluster/glusterfs as alternative.

**Comment by taraspos** [comment]
@cpxPratik sorry. You didn't quite get the issue I'm having. It is not completely related to the current one, so I created a new one - #1314.
