### ISSUE TITLE
curl -sSL https://dl.bintray.com/emccode/rexray/install returns Forbidden!

### ISSUE THREAD

**Issue by cnjr2** [rexray/rexray#1216]
# Summary
I am trying to install rexray with the following command:

```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable
```

However the response from `curl -sSL https://dl.bintray.com/emccode/rexray/install` is:

```
Forbidden!
```
## Expected Behavior

Rexray should be installed.

## Actual Behavior

The URL returns `Forbidden!`

## Steps To Reproduce

```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable
```

gives:

```
sh: line 1: Forbidden!: command not found
```

**Comment by cnjr2** [comment]
sorry! found the new link 😅

**Comment by mekasone** [comment]
@cnjr2 Can you share that link, thanks. 
(ran into the same challenge)

**Comment by clintkitson** [comment]
`https://dl.bintray.com/rexray/rexray/install`

**Comment by chuksleo** [comment]
In case any one run into this issue here is what i did when i had same issues seems the url for rexray changed

`   curl -sSL https://rexray.io/install | sh -s -- stable 0.6.3`

Cheers!!!

**Comment by chuksleo** [comment]
In case any one run into this issue here is what i did when i had same issues seems the url for rexray changed

`   curl -sSL https://rexray.io/install | sh -s -- stable 0.6.3`

Cheers!!!
