### ISSUE TITLE
Link to Slack (and Slack confusing channel)

### ISSUE THREAD

**Issue by Getty** [rexray/rexray#1222]
The link to the slack should always directly include the channel name:

https://codecommunity.slack.com/channels/project-rexray

Also there is a #rexray channel on the Slack, that MIGHT BE confusing :) (It _WAS_ confusing to me hehe)

**Comment by codenrhoden** [comment]
Hi @Getty,

Totally agreed -- I'll get links to that channel updated.

As for the #rexray channel, I'm not sure who created it, but I'll see if I can get it removed because yes, that will only cause confusion!
