### ISSUE TITLE
error: service startup failed: agent: mod init failed: error initializing instance ID cache

### ISSUE THREAD

**Issue by hitomidennis** [rexray/rexray#1242]
error: service startup failed: agent: mod init failed: error initializing instance ID cache

somebody here encountering "error: service startup failed: agent: mod init failed: error initializing instance ID cache" when doing a rexray start

Thank you

**Comment by clintkitson** [comment]
Hello @hitomidennis,

Typically this error happens when REX-Ray is misconfigured or you are trying to start it on a host that isn't compatible. Can you describe which provider you are trying to use when getting this error?

**Comment by hitomidennis** [comment]
Hi Clint,

Apology for late reply,

Already resolved after i raised the issue. Just to contribute on the troubleshooting. I am using AWS provider and AWS allow only EFS to be mounted on their EC2 instance of same region regardless of availability zones. so if you are trying to use EFS outside their VPC or infrastructure it will fail the rexray handshake

**Comment by aking1012** [comment]
Thanks for this.  So, no testing setting up efs or ebs on your laptop to try out rexray without spinning up an instance and you can't access those shares from your local laptop.  Good to know.  This should be documented in the examples.
