### ISSUE TITLE
docker volume inspect returns inconsistent driver options and labels

### ISSUE THREAD

**Issue by yunhee-l** [rexray/rexray#1250]
# Summary
Using rexray/ebs, driver options and labels are not returned when ```docker volume inspect``` is called on a different ec2 instance

# Bug Reports
Calling ```docker volume inspect``` on the same EBS volume from 2 different ec2 instances return inconsistent result. On the instance from which the ```docker volume create``` was issued, "Options" and "Labels" fields are correctly populated. On a different instance, they are always null.

## Version
```rexray version``` doesn't work when rexray is installed through ```docker plugin install```. However, this was the latest version (rexray/ebs:latest) as of Aug 13 2018, so I believe it is v0.11.3.
This is a snippet from ```docker plugin inspect``` which maybe relevant:
```
        ...
        "Id": "fef1d260ec6ef247a8f2b6d5f56087ac62aabd555a336786595c7080555b9db8",
        "Name": "rexray/ebs:latest",
        "PluginReference": "docker.io/rexray/ebs:latest",
        ...
```

## Expected Behavior
```docker volume inspect``` result should be consistent  for the same volume, regardless of where the call was issued from.

## Actual Behavior
"Options" and "labels" fields are null if the ```docker volume inspect``` is called from an instance that didn't create the volume under inspection.

## Steps To Reproduce
1. I installed rexray using docker plugin command on **ec2 instance 1**, with correct aws creds configured: ```docker plugin install rexray/ebs ```
2. Then created an EBS volume with driver options and labels:
```
$ docker volume create --driver rexray/ebs \
> --opt size=5 \
> --opt volumetype=gp2 \
> --label domain=test \
> ebsvol
```
3. Inspecting the created volume on the same instance returns Options correctly populated:
```
$ docker volume inspect ebsvol
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "rexray/ebs:latest",
        "Labels": {
            "domain": "test"
        },
        "Mountpoint": "/var/lib/docker/plugins/fef1d260ec6ef247a8f2b6d5f56087ac62aabd555a336786595c7080555b9db8/rootfs",
        "Name": "ebsvol",
        "Options": {
            "size": "5",
            "volumetype": "gp2"
        },
        "Scope": "global",
        "Status": {
            "availabilityZone": "us-west-2c",
            "fields": null,
            "iops": 100,
            "name": "ebsvol",
            "server": "ebs",
            "service": "ebs",
            "size": 5,
            "type": "gp2"
        }
    }
]
```
4. On a different ecs instance, say **ec2 instance 2**, where rexray/ebs is installed in the same manner as in step 1 above using the same creds, ebsvol is discoverable through ```docker volume ls```. However, docker volume inspect result returns null for "Options" and "Labels" fields:
```
$ docker volume inspect ebsvol
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "rexray/ebs:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/172a1a453cd6ef55d44e9fb9036c7dc92e9c8785299d3c79aebf8c6c30d92c46/rootfs",
        "Name": "ebsvol",
        "Options": null,
        "Scope": "global",
        "Status": {
            "availabilityZone": "us-west-2c",
            "fields": null,
            "iops": 100,
            "name": "ebsvol",
            "server": "ebs",
            "service": "ebs",
            "size": 5,
            "type": "gp2"
        }
    }
]

```

**Comment by clintkitson** [comment]
Hello @yunhee-l,

The parameters in the "Status" field are what REX-Ray is able to return. The "Options" are stored solely by Docker. If you want those options globally visible then Docker Swarm would likely need to be used so it carries over the options among hosts. I am not 100% sure whether it does this today.

**Comment by yunhee-l** [comment]
Closing this, we have implemented workaround to allow customers to choose name-only comparison or full config comparison for volumes. Thank you.
