### ISSUE TITLE
RexRay Binary(s) file permissions preventing access

### ISSUE THREAD

**Issue by carl-utter** [rexray/rexray#1277]
# Summary
The permissions applied to the RexRay Binaries @ [https://dl.bintray.com/emccode/rexray/stable/](https://dl.bintray.com/emccode/rexray/stable/) are preventing download access

# Bug Reports
Using `curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable 0.6.3` returns 
> sh: line 1: Forbidden!: command not found

Clicking directly in browser @ [https://dl.bintray.com/emccode/rexray/stable/0.6.3/rexray_0.6.3-1_amd64.deb](https://dl.bintray.com/emccode/rexray/stable/0.6.3/rexray_0.6.3-1_amd64.deb) returns
> Forbidden!

## Expected Behavior
Using Curl or Direct link click in Browser should allow download access to user specified version

## Actual Behavior
Access is Forbidden regardless of user specified version

## Steps To Reproduce
1) from terminal; `curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable 0.6.3`
2) from browser; [https://dl.bintray.com/emccode/rexray/stable/0.6.3/rexray_0.6.3-1_amd64.deb](https://dl.bintray.com/emccode/rexray/stable/0.6.3/rexray_0.6.3-1_amd64.deb)

**Comment by carl-utter** [comment]
@clintkitson is there any chance you or somebody else on the RexRay team could confirm this issue?

**Comment by carl-utter** [comment]
The fix for this was to use the install path that has been [updated in rexray documentation](https://rexray.readthedocs.io/en/latest/user-guide/installation/#install-via-curl):

`curl -sSL https://rexray.io/install | sh -s -- stable 0.6.3`

**Comment by manofthelionarmy** [comment]
> 
> 
> The fix for this was to use the install path that has been [updated in rexray documentation](https://rexray.readthedocs.io/en/latest/user-guide/installation/#install-via-curl):
> 
> `curl -sSL https://rexray.io/install | sh -s -- stable 0.6.3`

You're a hero. I was having an issue for installing this. Thank you :)
