### ISSUE TITLE
Using docker service create with docker plugin rexray/dobs

### ISSUE THREAD

**Issue by pascalandy** [rexray/rexray#1294]
## Summary
Can't use the docker plugin along my docker service create.

## New Feature
nope

## Bug Reports
maybe ?

## Version
rexray: command not found. Normal: it's a docker plugin)

## Expected Behavior
Use my docker service create scripts as usual.

# Steps To Reproduce

I'm using the Digital Ocean block storage DOBS.
On my 3 nodes I ran this and it looks normal.

```
docker plugin install rexray/dobs --grant-all-permissions \
  DOBS_REGION=nyc3 \
  DOBS_TOKEN=1231321321321321321321321321321321321321321321
```

## from docker docs
I want to use my docker service create scripts as usual. Something like:

(https://docs.docker.com/engine/extend/plugins_services/)

```
$ docker service create --name my-service --mount type=volume,volume-driver=tiborvass/sample-volume-plugin,source=pluginVol,destination=/tmp busybox top

$ docker service ls
z1sj8bb8jnfn  my-service   replicated  1/1       busybox:latest
```

## docker service create

In this case, I want to run my ghost container using dobs (instead of bind). So I did this:

```
docker service create \
  --name=${CTN_ghost} \
  ...
  --mount type=volume,volume-driver=rexray/dobs,source=${ENV_DEPLOY_ID}-gstcontent,destination=/var/lib/ghost/content \
  ...
  ${IMG_ghost};
```

## but the service never starts:

```
fodk6kdmvw2tasrp29s2pl0x2
overall progress: 0 out of 1 tasks
1/1: create 1001-gstcontent: VolumeDriver.Create: docker-legacy: Create: 10…
```

## docker inspect

```
  "Mounts": [
      {
          "Type": "volume",
          "Source": "1001-gstcontent",
          "Target": "/var/lib/ghost/content",
          "VolumeOptions": {
              "DriverConfig": {
                  "Name": "rexray/dobs"
              }
          }
      }
  ],
```

**Comment by pascalandy** [comment]
**Question 1**) As I don't use docker-compose here, can someone share few examples about writing this:

```
--mount type=volume,volume-driver=rexray/dobs,source=${ENV_DEPLOY_ID}-gstcontent,destination=/var/lib/ghost/content
```

**Question 2**) how to define size?

**Question 3**) Subdirectories. I'm running about 100 of those web servers. It means 100 volumes !! Could I simply have one volume where I could share sub-folders? I feel it's crazy to have so many volumes.

Thank you very much folks!

**Comment by pascalandy** [comment]
Experimenting with a simple docker run:

So far this works:

```
docker volume create --driver=rexray/dobs --name=caddytest --opt=size=1

docker run -d \
  --name caddytest \
  -p 2015:2015 \
  -v $(pwd)/tmpdata:/tmpdata \
  -v caddytest:/srv \
  devmtl/caddyfire:edge_2019-01-17_15H17
```

**Comment by sagebind** [comment]
I use compose files, but I'm sure there's a command line equivalent for everything. Size can be specified via the aptly-named `size` driver option (which seems under-documented). It looks like this:

```yaml
version: '3.7'

services:
  app:
    image: my-image
    volumes:
      - data:/var/data

volumes:
  data:
    name: my-do-volume
    driver: rexray/dobs
    driver_opts:
      size: 4 # Size in GiB
```

The equivalent command line syntax _should_ be according to the docs:

```
--mount type=volume,source=my-do-volume,destination=/var/data,volume-driver=rexray/dobs,volume-opt=size=4
```

I'm not sure why that might not work though. I use rexray/dobs heavily in production and have seen very few issues. What version of the Docker engine are you running?

https://docs.docker.com/engine/reference/commandline/service_create/#add-bind-mounts-volumes-or-memory-filesystems

**Comment by pascalandy** [comment]
Thanks for jumping in! I also realized that the rexray/dobs is locked by the node using it defeats the whole purpose of having a stateful container that can come and go to a multitude of nodes.

For now I'll stick to Resilio to share a common directory between my nodes.
