### ISSUE TITLE
RDB volume is empty inside the container

### ISSUE THREAD

**Issue by r3pek** [rexray/rexray#1296]
# Summary
When using the rexray plugin to mount rbd volumes, the volumes are mounted on the host correctly, but the container only sees and empty directory, even though the "mount" reports the volume as mounted.

# Bug Reports
This section is for issues that relate to discovered problems or bugs.

## Version
latest version of rexray/rbd from docker hub.

## Expected Behavior
Host and container should see the device contents

## Actual Behavior
Only the host sees the contents, containers see and empty directory

## Steps To Reproduce
1. docker plugin install rexray/rbd
2. docker volume ls | grep rbd # confirm that the existing volumes are listed
3. docker run -it -v <device>:/data --volume-driver=rexray/rbd busybox sh
4. ls /data

**Comment by r3pek** [comment]
OK... I found the issue. rexray creates a directory inside the device with the path to the mountpoint inside the container, never using the root mountpoint itself. So, because I mounted the volume as `-v example:/data`, it creates a /data directory inside the mounted device instead of just mounting the device inside /data inside the container. (hope I was clear enough in here).

Any way to adjust this behaviour?

**Comment by f1-outsourcing** [comment]
How did you configure rexray for ceph? I cannot even do rexray volume ls, I have this issue https://github.com/rexray/rexray/issues/1297

**Comment by r3pek** [comment]
@f1-outsourcing i used the plugin method. Just `docker plugin install rexray/rbd` on each node

**Comment by thielj** [comment]
@r3pek I had the same problem. Try passing these parameters:

```
docker plugin install rexray/rbd \
        LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_ROOTPATH=/ \
        LINUX_VOLUME_ROOTPATH=/
```

The first one will mount / instead of data, the second will prevent rexray from creating the /data folder on the volume each time you mount.

**Comment by r3pek** [comment]
@thielj that was it! thx!! :)
