### ISSUE TITLE
S3FS docker plugin breaks after some time, volume mounting fails from then on

### ISSUE THREAD

**Issue by BFMeenink** [rexray/rexray#1336]
# Summary
In our production environment we connect several CoreOS instances to each other, with one of the scripts installing `rexray/s3fs:0.11.4` as a docker plugin, to enable accessing several AWS S3 buckets. This functions exactly as desired most of the time, but sometimes randomly stops working. 

Once we find that one of the buckets does not mount properly anymore, and we mount one of the other ones which hasn't been used so far (`docker container run -it --rm -v s3-backup-bucket:/mnt/s3 busybox`), we get journalctl logging detailing a successful mount, but showing a failure upon container exiting due to failure to dismount. As expected, succeeding mounts fail. This leads to ultimately all s3 mounts becoming unreachable for that particular worker node.

Dis- & Enabling the plugin does not solve the issue, removing & re-installing the plugin fixes each bucket for a single time, showing failure during dismounting on exit again. Rebooting the docker daemon, which is a no-go for production environments, fixes the issue until at some point it fails again.

The above scenario is detailed & demonstrated in the steps to reproduce.

Since usually we find the plugin broken through thresholds of minimum number of back-ups being broken, by the time we check the logs have been rotated -> I can not find the exact moment of the plugin breaking.

## Version
```shell
core@prod-1-worker-10.0.21.50 ~ $ uname -a
Linux prod-1-worker-10.0.21.50 4.19.34-coreos #1 SMP Mon Apr 22 20:32:34 -00 2019 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux
core@prod-1-worker-10.0.21.50 ~ $ docker info
...
Server Version: 18.06.3-ce
Kernel Version: 4.19.34-coreos
Operating System: Container Linux by CoreOS 2079.3.0 (Rhyolite)
...
core@prod-1-worker-10.0.21.50 ~ $ docker plugin inspect <rexray/s3fs plugin id>
...
        "PluginReference": "docker.io/rexray/s3fs:0.11.4",
...
```
In short: AWS EC2 instances with CoreOS 2079.3.0, docker 18.06.3-ce & rexray/s3fs:0.11.4.

## Expected Behavior
Not to break and/or to restore itself in time.

## Actual Behavior
Stays broken & requires a docker daemon restart for a proper fix, meaning services that do not use S3 are affected as well.

## Steps To Reproduce
I'm still working on a from working properly to broken guide, which I'll add if I find it, but once broken I can 're-break' it through:

1. Cancel/kill/stop/rm any job involving S3 usage
2. `docker volume ls` should now show the S3 buckets (that fail to mount)
```
DRIVER              VOLUME NAME
local               48ad58d7cdc5d4ee536f1f48372938a3c88d368d8aba950ffb170be120f1eb12
local               87d2870e8bdf17cc8f0d0454c0b76d0b9712fd074af5fc5ac3c8bffd100c42aa
local               a846fb1bf44d067c29d83f3b13eed74e04ce2a66d9585cfecb7813cbceb00ada
s3fs:latest         remote-s3-bucket1
s3fs:latest         remote-s3-bucket2
s3fs:latest         remote-s3-bucket3
...
```
3. `docker plugin disable -f s3fs && docker plugin rm -f s3fs`
`-f` are required due to https://github.com/rexray/rexray/issues/1176, I think, as I've killed literally every job that had something to do with S3. Without, I get blocked by 'still in use'.
4. `docker volume ls` should now no longer show the S3 buckets
5.  
```shell
docker plugin install --disable --grant-all-permissions rexray/s3fs:0.11.4 --alias s3fs \
  REXRAY_LOGLEVEL=debug \
  S3FS_ACCESSKEY=<access-key> \
  S3FS_SECRETKEY=<secret-key> \
  S3FS_REGION=eu-west-1 \
  LINUX_VOLUME_FILEMODE=0777 \
  S3FS_OPTIONS="allow_other,iam_role=auto,umask=000"
docker plugin enable --timeout 120 s3fs
```
Logs: https://gist.github.com/Forvaine/1465f6e045a1c60168724a84e60435a3
6. `docker volume ls` should now show the present S3 buckets, again
```
DRIVER              VOLUME NAME
local               48ad58d7cdc5d4ee536f1f48372938a3c88d368d8aba950ffb170be120f1eb12
local               87d2870e8bdf17cc8f0d0454c0b76d0b9712fd074af5fc5ac3c8bffd100c42aa
local               a846fb1bf44d067c29d83f3b13eed74e04ce2a66d9585cfecb7813cbceb00ada
s3fs:latest         remote-s3-bucket1
s3fs:latest         remote-s3-bucket2
s3fs:latest         remote-s3-bucket3
...
```
Logs: https://gist.github.com/Forvaine/1cbf891dcec67f18b9e1f64d4c0d1b84
7. `docker container run -it --rm -v remote-s3-bucket1:/s3fs busybox` should now work
```sh
core@prod-1-worker-10.0.21.50 /var/lib/docker $ docker container run -it --rm -v remote-s3-bucket1:/s3fs busybox
/ #
```
Logs: https://gist.github.com/Forvaine/4ee8ebaf08fb0d7231bd8605db83fe15
8. Inside the container: `exit`
Logs: https://gist.github.com/Forvaine/d63c4e399f818ce372ef0b1c1bb8a391
9. `docker container run -it --rm -v remote-s3-bucket1:/s3fs busybox` should now be broken again:
```sh
core@prod-1-worker-10.0.21.50 /var/lib/docker $ docker container run -it --rm -v remote-s3-bucket1:/s3fs busybox
/run/torcx/bin/docker: Error response from daemon: error while mounting volume '': VolumeDriver.Mount: docker-legacy: Mount: remote-s3-bucket1: failed: error mounting s3fs bucket.
```
Logs: https://gist.github.com/Forvaine/be62e216568bf5b26bf8ca2ab73eb919

## Configuration Files
`docker plugin inspect s3fs:latest`
```json
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "REX-Ray FUSE Driver for Amazon Simple Storage Service (S3FS)",
            "DockerVersion": "18.06.1-ce",
            "Documentation": "https://github.com/thecodeteam/rexray/.docker/plugins/s3fs",
            "Entrypoint": [
                "/rexray.sh",
                "rexray",
                "start",
                "-f",
                "--nopid"
            ],
            "Env": [
                {
                    "Description": "",
                    "Name": "REXRAY_LOGLEVEL",
                    "Settable": [
                        "value"
                    ],
                    "Value": "warn"
                },
                {
                    "Description": "",
                    "Name": "LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_ROOTPATH",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "LINUX_VOLUME_ROOTPATH",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "LINUX_VOLUME_FILEMODE",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "HTTP_PROXY",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "S3FS_ENDPOINT",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "S3FS_ACCESSKEY",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "S3FS_DISABLEPATHSTYLE",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "S3FS_MAXRETRIES",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "S3FS_OPTIONS",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "S3FS_REGION",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "S3FS_SECRETKEY",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CSI_ENDPOINT",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "The name of the CSI plug-in used by the CSI module.",
                    "Name": "X_CSI_DRIVER",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "A flag that disables the CSI to libStorage bridge.",
                    "Name": "X_CSI_NATIVE",
                    "Settable": [
                        "value"
                    ],
                    "Value": "false"
                }
            ],
            "Interface": {
                "Socket": "rexray.sock",
                "Types": [
                    "docker.volumedriver/1.0"
                ]
            },
            "IpcHost": false,
            "Linux": {
                "AllowAllDevices": true,
                "Capabilities": [
                    "CAP_SYS_ADMIN"
                ],
                "Devices": null
            },
            "Mounts": [
                {
                    "Description": "",
                    "Destination": "/dev",
                    "Name": "",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": null,
                    "Source": "/dev",
                    "Type": "bind"
                }
            ],
            "Network": {
                "Type": "host"
            },
            "PidHost": false,
            "PropagatedMount": "/var/lib/rexray",
            "User": {},
            "WorkDir": "",
            "rootfs": {
                "diff_ids": [
                    "sha256:bbb8bdd9792301285c4b73fe541acab7d65ea9396b95bd2255ae2a6075be4b5f"
                ],
                "type": "layers"
            }
        },
        "Enabled": true,
        "Id": "47e7a1618608ff2423824400345618f2f04da6e279bc181c6af62b84233fa75f",
        "Name": "s3fs:latest",
        "PluginReference": "docker.io/rexray/s3fs:0.11.4",
        "Settings": {
            "Args": [],
            "Devices": [],
            "Env": [
                "REXRAY_LOGLEVEL=debug",
                "LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_ROOTPATH=",
                "LINUX_VOLUME_ROOTPATH=",
                "LINUX_VOLUME_FILEMODE=0777",
                "HTTP_PROXY=",
                "S3FS_ENDPOINT=",
                "S3FS_ACCESSKEY=<access key>",
                "S3FS_DISABLEPATHSTYLE=",
                "S3FS_MAXRETRIES=",
                "S3FS_OPTIONS=allow_other,iam_role=auto,umask=000",
                "S3FS_REGION=eu-west-1",
                "S3FS_SECRETKEY=<secret key>",
                "CSI_ENDPOINT=",
                "X_CSI_DRIVER=",
                "X_CSI_NATIVE=false"
            ],
            "Mounts": [
                {
                    "Description": "",
                    "Destination": "/dev",
                    "Name": "",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": null,
                    "Source": "/dev",
                    "Type": "bind"
                }
            ]
        }
    }
]
```

## Logs
Instead of pasting the full logs here, I've opted to paste them as gists/snippets in between the steps to reproduce. Let me know if you'd still prefer a full log.

**Comment by clarity99** [comment]
experiencing same thing... no response to this since september, is someone still maintaining this project?

**Comment by Makeshift** [comment]
Looks like I'm having this exact issue. I don't suppose you ever found a solution, @Forvaine ?

**Comment by gaul** [comment]
s3fs exiting is a symptom of a crash.  You may be able to work around this by unmounting and remounting the path.  I am more familiar with s3fs than rexray, but it appears that rexray uses the host s3fs.  Please ensure that you are using a recent s3fs version like 1.87 since some LTS distributions like Ubuntu 18.04 ship 1.82 has many long-fixed bugs.  If upgrading does not resolve your symptoms, you need to collect log data, e.g., `s3fs -f -d`, to see why s3fs exited.

**Comment by BFMeenink** [comment]
@Makeshift We kind of didn't, we just worked around it by removing our need for it. We use Restic for backups and instead of running it with a s3fs enabled volume mount to work on, it also supports just working with AWS by giving it an S3 path and some AWS access/secret keys. S3FS has been phased out at this point for us.

**Comment by Makeshift** [comment]
I ended up using S3FS directly on the ECS host. Not ideal, since the ECS hosts now depend on the stuff they're hosting, but until we can refactor the application to call S3 directly, this will have to do.

**Comment by iFloris** [comment]
While not exactly the same thing as rexray, this docker volume plugin also allows you to use docker volumes with S3 (and many other providers) https://github.com/sapk/docker-volume-rclone
It's not quite as convenient, you have to specify each bucket separately. But if you are running into the above volume mounting problem with rexray then this might be an alternative to consider.

**Comment by bizmate** [comment]
hi all. Is anyone of you using a different plugin to implement the same bucket loading requirement since this plugin might not be maintained anymore?

**Comment by iFloris** [comment]
@bizmate we have moved to Rclone with https://github.com/sapk/docker-volume-rclone. When mounted on all hosts, containers are able to move around.

**Comment by bizmate** [comment]
hi @iFloris i just read through its example and the config at https://rclone.org/s3/#amazon-s3

I have not fully tried yet but with the rexray plugin i could just install the S3 one and i could straight away see the buckets from S3 as existing volumes. Do you know is something similar is possible in rclone? 
I am provisioning a bucket with configuration so i do not want to create the volume with docker but just load the bucket as a volume and consume it as an existing bucket in other containers/services

**Comment by iFloris** [comment]
Hello @bizmate I think this is more something to discuss on https://github.com/sapk/docker-volume-rclone. See my earlier message as well https://github.com/rexray/rexray/issues/1336#issuecomment-723420132.

**Comment by BFMeenink** [comment]
Closing this issue as it's never going to get solved anyway.

**Comment by gaul** [comment]
As I said in https://github.com/rexray/rexray/issues/1336#issuecomment-691417255, please make sure you are using a recent version of s3fs.  The Ubuntu 18.04 host-provided one has many bugs that cause crashes that were fixed years ago.
