### ISSUE TITLE
Unable to install rexray/rbd Docker Plugin - rexray.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by fooxytv** [rexray/rexray#1349]
Resolved

**Comment by fooxytv** [comment]
Resolved.

**Comment by yalezhangk** [comment]
I also encountered the same problem. How can I solve it？
My docker version: Server Version: 20.10.14(Ubuntu 20.04)

**Comment by fooxytv** [comment]
@yalezhangk If I can recall, I think it was due to a permissions issue.
