### ISSUE TITLE
Openstack : CACERT ?

### ISSUE THREAD

**Issue by codenrhoden** [rexray/rexray#952]
@davvdg commented on [Thu Sep 22 2016](https://github.com/codedellemc/libstorage/issues/272)

Hi, to access my private openstack cloud with openstack cli I need to provide a (path to a) certificate through the OS_CACERT env. How should I configure that in rexray and is it handled ?

Thanks

David

---

@codenrhoden commented on [Wed Mar 15 2017](https://github.com/codedellemc/libstorage/issues/272#issuecomment-286905089)

something to check along with #182 and #243 

---

@MatMaul commented on [Wed Apr 05 2017](https://github.com/codedellemc/libstorage/issues/272#issuecomment-291982272)

It doesn't look like it is supported by gophercloud with an explicit option. However it is possible that we could override an http client somewhere to do so, to be checked.

---

@olivibernard commented on [Mon May 15 2017](https://github.com/codedellemc/libstorage/issues/272#issuecomment-301692897)

Hi there,
Is this available in release 0.9.0 ?
I have the same request : how to configure rexray/cinder and specify openstack certs ?
Thanks

**Comment by mmariani** [comment]
Hello,
I don't use your project, but have implemented the feature for linuxkit: https://github.com/linuxkit/linuxkit/pull/2620

Regards

**Comment by MatMaul** [comment]
Thanks, looks simple enough to be ported.

**Comment by MatMaul** [comment]
@codenrhoden do you think you can test ?
